# Generated by Django 3.0.2 on 2020-01-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='marque',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='vetement',
            field=models.CharField(max_length=255),
        ),
    ]
