# Generated by Django 3.0.2 on 2020-01-21 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200121_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='vetement',
            new_name='typeVetement',
        ),
    ]
